kind: ConfigMap
apiVersion: v1
metadata:
  name: maven-settings
data:
  settings.xml: |-
    <?xml version="1.0" encoding="UTF-8" standalone="no" ?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
      <profiles>
        <profile>
          <id>default-profile</id>
          <repositories>
            <repository>
              <id>jboss-enterprise-maven-repository-ga</id>
              <url>https://maven.repository.redhat.com/ga/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
            <repository>
              <id>jboss-enterprise-maven-repository-ea</id>
              <url>https://maven.repository.redhat.com/earlyaccess/all/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </repository>
          </repositories>
          <pluginRepositories>
            <pluginRepository>
              <id>jboss-enterprise-maven-plugin-repository-ga</id>
              <url>https://maven.repository.redhat.com/ga/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </pluginRepository>
            <pluginRepository>
              <id>jboss-enterprise-maven-plugin-repository-ea</id>
              <url>https://maven.repository.redhat.com/earlyaccess/all/</url>
              <releases>
                <enabled>true</enabled>
              </releases>
              <snapshots>
                <enabled>false</enabled>
              </snapshots>
            </pluginRepository>
          </pluginRepositories>
        </profile>
      </profiles>
      <activeProfiles>
        <activeProfile>default-profile</activeProfile>
      </activeProfiles>
    </settings>
