apiVersion: v1
kind: ConfigMap
metadata:
  name: 'post-config'
data:
  post-config.sh: >
    #!/bin/sh 

    printf '\n' >> "${CONFIG_INSTANCE_DIR}"/etc/artemis.profile 

    echo 'JAVA_ARGS="$JAVA_ARGS -Djavax.net.ssl.trustStore=/amq/extra/configmaps/rhsso-truststore/truststore.jks -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.trustStoreType=jks"' >> ${CONFIG_INSTANCE_DIR}/etc/artemis.profile 

    echo "/etc/artemis.profile updated" 

    cat /amq/scripts/post-config.sh
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhsso-truststore
binaryData:
  truststore.jks: > 
    {{ .Files.Get "truststore/truststore.jks" | b64enc }}