amq:
  initImage: amq-init:latest
  image: placeholder
  build:
    git:
      uri: 'https://github.com/ippul/rhsso-amq-security-plugin-example.git'
    contextDir: /rhsso-amq-security-plugin



rhsso:

clients:
  build:
    git:
      uri: 'https://github.com/ippul/rhsso-amq-security-plugin-example.git'
    contextDir: /amq-clients-example
    output:
      to:
        kind: ImageStreamTag
        name: 'amq-clients-example:latest'

