amq:
  initImage: amq-init:latest
  image: placeholder
  build:
    git:
      uri: 'https://github.com/ippul/rhsso-amq-security-plugin-example.git'
    contextDir: /rhsso-amq-security-plugin
    initImage:
      base:
        tag: '7.10-38.1675807822'
    libs:
      keycloak:
        version: '15.0.4.redhat-00004'

rhsso:

clients:
  build:
    git:
      uri: 'https://github.com/ippul/rhsso-amq-security-plugin-example.git'
    contextDir: /amq-clients-example
    output:
      to:
        kind: ImageStreamTag
        name: 'amq-clients-example:latest'

