apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: redhat-sso
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: true
  keycloakDeploymentSpec:
    experimental:
      volumes:
        items:
          - configMaps:
              - sso-cli-script
            mountPath: /opt/eap/extensions
            name: startupcliscripts
