approveManualInstallPlanViaHook: true

installPlanApproverAndVerifyJobsImage: 'quay.io/openshift/origin-cli:4.12'

operators:
- channel: 'stable'
  installPlanApproval: 'Manual'
  name: 'rhsso-operator'
  source: 'redhat-operators'
  sourceNamespace: 'openshift-marketplace'
  csv: 'rhsso-operator.7.6.8-opr-001'

operatorGroups:
- createNamespace: false
  targetOwnNamespace: true
